### ISSUE TITLE
Binary Install Should Use Official Prometheus Binaries

### ISSUE THREAD

**Issue by ewr** [elijah/chef-prometheus#33]
The Prometheus project recently started building binaries with releases:

https://github.com/prometheus/prometheus/releases

It seems like they're a little inconsistent about the platforms, but I would imagine that'll get sorted shortly. I'll ping the mailing list about that.

Using these instead of homerolled binaries should be a good plus for release cadence and officialness. I had intended to just submit a PR for this, but that hasn't happened yet.

**Comment by tuahk** [comment]
Thanks @ewr for opening this issue. We should definitely start using those binaries.

**Comment by rayrod2030** [comment]
Yeah this is a really nice improvement.  Will try to get to this over the weekend.  Thanks @ewr!

**Comment by Magrath** [comment]
I made a start towards this in #38.

**Comment by elijah** [comment]
Merged earlier.
