### ISSUE TITLE
Prometheus config format switched from ASCII protobufs to YAML

### ISSUE THREAD

**Issue by gbagnoli** [elijah/chef-prometheus#34]
PR: https://github.com/prometheus/prometheus/pull/680
Here the [announcement on the mailing list](https://groups.google.com/forum/#!topic/prometheus-developers/cuutf6PCKvs)

Judging by the commit history on the github page, versions after `0.13.3` (https://github.com/prometheus/prometheus/commit/43b41c56ce469cdaa94447541693578c5ec16a91) are using the new yaml config format.

Currently the `source` installation method is broken, `binary` works as the binary itself is old (the sourceforge page says it has been updated on 2015-03-18)

**Comment by unbrice** [comment]
Would you accept a PR that would drop support of versions <= 0.13.3 in favor of versions >=0.14, hardcoding the use of the new format?
The target configurable settings - among other things - has changed a bit. Supporting only newer versions going forward removes the need of a common configuration abstracting away the changes. Users of older Prometheus versions could still use older versions of the recipe until they upgrade.

**Comment by rayrod2030** [comment]
@unbrice Yes absolutely I think the best solution would be to support >=0.14 as there have been lots of changes.  Would totally welcome a PR as I haven't had as much time as I'd like to have had to upgrade this cookbook.
