### ISSUE TITLE
AlertManager support

### ISSUE THREAD

**Issue by unbrice** [elijah/chef-prometheus#37]
How do you think [AlertManager](https://github.com/prometheus/alertmanager) should be supported? The options I see are:
- Creating a new cookbook.
- Adding it as a recipe inside the current cookbook.
- Enabling it via an attribute within the current recipes.

This goes from the conceptually cleanest - but with the most boilerplate - to the least redundant - but the least scalable.

**Comment by elijah** [comment]
This was merged a couple years ago.  Closing issue; it's also been refactored (thanks to @JavierZunzunegui IIRC) to support both binary and source deploys.
