### ISSUE TITLE
bluepill dependency should be optional

### ISSUE THREAD

**Issue by erkki** [elijah/chef-prometheus#47]
The current hard dependency on bluepill should be optional, it's optional in the service recipe (not a default for any platform) and a burden to manage (as an dependency) for people who do not use it.

In this specific case bluepill depends on rsyslog ~2 and prevents an upgrade of the rsyslog cookbook.

**Comment by elijah** [comment]
I have converted this to a suggests and have actually disabled the bluepill test-kitchen suites for now.
