### ISSUE TITLE
Installing newer version fails

### ISSUE THREAD

**Issue by aktarali** [elijah/chef-prometheus#54]
Hi;

I'm trying to install version 1.0.2. Updated the attributes and it fails with the following messages:

```
* Unable to parse SHA reference for '1.0.2' in repository 'https://github.com/prometheus/prometheus.git'. Verify your (case-sensitive) repository URL and revision.
`git ls-remote 'https://github.com/prometheus/prometheus.git' '1.0.2*'` output: 
================================================================================
Error executing action `checkout` on resource 'git[/var/chef/cache/prometheus-1.0.2]'
```

Please advise.

Thanks
Ali.

**Comment by AlexeyDemidov** [comment]
You need to specify `git_revision` and set it to `v1.0.2` (note leading symbol `v`)

**Comment by aktarali** [comment]
Tried doing that and I'm getting the following:
  * bash[compile_prometheus_source] action run
    
    ================================================================================
    Error executing action `run` on resource 'bash[compile_prometheus_source]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '2'
    ---- Begin output of "bash"  "/tmp/chef-script20160916-2914-flovrx" ----
    STDOUT: 
    STDERR: package github.com/prometheus/promu: cannot download, $GOPATH not set. For more details see: go help gopath
    make: *** [promu] Error 1
    ---- End output of "bash"  "/tmp/chef-script20160916-2914-flovrx" ----
    Ran "bash"  "/tmp/chef-script20160916-2914-flovrx" returned 2


Seems the newer versions needs GOPATH specified. Doing that breaks everything as things need to be built under GOPATH. The rest of the cookbook needs modifying if this is to work. 

Can someone please assist?

Ali.

**Comment by raju-divakaran** [comment]
Was anyone able to overcome this situation ?

**Comment by elijah** [comment]
I think there are 2 different bugs here.  One is around the version, one around the known gopath problem in one of the other issues.
