### ISSUE TITLE
golang is dependency for recipe::source

### ISSUE THREAD

**Issue by AlexeyDemidov** [elijah/chef-prometheus#55]
If Prometheus is installed from the source it needs golang installed on the target system but this dependency isn't specified anywhere.

**Comment by elijah** [comment]
I'm adding dependencies on golang and an include_recipe golang::default to the source recipe -- can you figure out what's up with the GOPATH and make suggestions on how we should revise the source recipe so that it actually works correctly?  [I tried it out locally and it fails midstream....]

**Comment by elijah** [comment]
I've made quite a few minor changes around GOPATH today; I don't have it (source builds) quite working yet but the golang recipe inclusion has been fixed for some time.
