### ISSUE TITLE
How to access web interface once the converge is done

### ISSUE THREAD

**Issue by mikimtm** [elijah/chef-prometheus#65]
I have done converge and test, then converge again and tried to access interaface at ip 10.xx.xx.xx:9090 but it is unreachable.

I am sure I am doing something wrong.

**Comment by allaire** [comment]
@gnufreex Make sure your firewall accept 9090. I personally prefer to setup nginx and proxy_pass to it

**Comment by elijah** [comment]
nginx or traefik in front of prometheus would both be excellent solutions here.
